[package]
name = "rosy_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = { version = "0.2.0", features = ["auto-color"] }
indoc = "2"
unicode_names2 = "0.6.0"
