[package]
name = "rosy_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2"
rosy_error = { git = "https://github.com/rosy-lang/rosy_error", branch = "main" }
unicode_names2 = "0.6.0"
